task: 'uformer_denoising_color_sidd'
model: 'Stripformer'
seed: 0
n_channels: 3  # 输入图像通道数
sigma: 15
path:
  pretrained_net: null
datasets:
  dataset_type: 'denoising'
  dataloader_shuffle: true
  dataloader_num_workers: 1
  dataloader_batch_size: 12
  train:
    state: 'Train'
    H_path: [ '/root/autodl-tmp/TrainData/SIDD/train/groundtruth' ]
    L_path: [ '/root/autodl-tmp/TrainData/SIDD/train/input' ]
    image_size: 64
  val:
    state: 'Val'
    H_path: [ 'E:\Data\SIDD\val\groundtruth' ]
    L_path: [ 'E:\Data\SIDD\val\input' ]
net:
  type: 'Stripformer'
  img_size: 64
optimizer:
  type: 'adam'
  learning_rate: 2.0e-4  # 学习率
  weight_decay: 0.0  # 权重衰减
  betas: [ 0.9, 0.999 ]
  eps: 1.0e-8
criterion:
  type: 'stripformer_loss'
scheduler:
  type: 'CosineAnnealingLR'
  T_max: 100
  eta_min: 1.0e-7
train:
  lossfn_weight: 1.0
  start_epoch: 0
  num_epochs: 100
  checkpoint_val: 1
  checkpoint_print: 1