# MB-TaylorFormer V2

task: 'MB-TaylorFormer V2'
seed: 0
n_channels: 3  # 输入图像通道数
sigma: 15
path:
  pretrained_net: null
datasets:
  dataset_type: 'denoising'
  dataloader_shuffle: true
  dataloader_num_workers: 1
  dataloader_batch_size: 12
  train:
    state: 'Train'
    H_path: [ 'E:\Data\SIDD\train\groundtruth' ]
    L_path: [ 'E:\Data\SIDD\train\input' ]
    image_size: 128
  val:
    state: 'Val'
    H_path: [ 'E:\Data\SIDD\val\groundtruth' ]
    L_path: [ 'E:\Data\SIDD\val\input' ]
net:
  type: 'mb_taylorformer_v2-B'
  in_chans: 3
  img_size: 128
  embed_dim: [ 24,48,72,96 ]
  num_blocks: [ 2,3,3,4 ]
  num_refinement_blocks: 4
  heads: [ 1,2,4,8 ]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  dual_pixel_task: False
  num_path: [ 2,2,2,2 ]
  qk_norm: 0.5
  offset_clamp: [ -3, 3 ]
optimizer:
  type: 'adamw'
  learning_rate: 2.0e-4  # 学习率
  weight_decay: 0.02  # 权重衰减
  betas: [ 0.9, 0.999 ]
  eps: 1.0e-8
criterion:
  type: 'charbonnier'
  eps: 1.0e-9
scheduler:
  type: 'CosineAnnealingLR'
  T_max: 70
  eta_min: 1.0e-7
train:
  lossfn_weight: 1.0
  start_epoch: 0
  num_epochs: 70
  checkpoint_val: 1
  checkpoint_print: 1