task: 'swinir_sr_classical_patch48_x2'  # classical image sr for x2
model: 'swinir'
dist: True  # 是否使用分布式训练
gpu_ids: [ 0, 1 ]
seed: 0
scale: 2  # 放大倍数
n_channels: 3  # 输入图像通道数
path:
  pretrained_net: null
datasets:
  dataset_type: 'sr'
  dataloader_shuffle: true
  dataloader_num_workers: 4
  dataloader_batch_size: 12
  train:
    dataroot_H: 'E:\Data\DIV2K\DIV2K_train_HR'
    dataroot_L: 'E:\Data\DIV2K\DIV2K_train_LR_unknown\X2'
    H_size: 24
  val:
    dataroot_H: 'E:\Data\Set14\original'
    dataroot_L: 'E:\Data\Set14\LRbicx2'
net:
  type: 'swinir'
  upscale: 2
  in_chans: 3
  img_size: 48
  window_size: 8
  img_range: 1.0
  depths: [ 6, 6, 6, 6, 6, 6 ]
  embed_dim: 180
  num_heads: [ 6, 6, 6, 6, 6, 6 ]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'
  init_type: 'default'
train:
  start_epoch: 0
  num_epochs: 1000000
  checkpoint_val: 5000
  checkpoint_save: 5000
  checkpoint_print: 200

  decay: 0.999


  G_param_strict: true
  E_param_strict: true

  optimizer:
    type: 'adam'
    learning_rate: 2.0e-4  # 学习率
    weight_decay: 0  # 权重衰减
    clipgrad: null # 梯度裁剪
    betas: [ 0.9, 0.999 ]
    reuse: true
  scheduler:
    type: 'MultiStepLR'
    milestones: [ 250000, 400000, 450000, 475000, 500000 ]
    gamma: 0.5
  criterion:
    loss_type: 'l1'
    weight: 1.0











