# Restormer_baseline

task: Restormer_Baseline
seed: 0
n_channels: 3  # 输入图像通道数
sigma: 15
path:
  pretrained_net: null
datasets:
  dataset_type: denoising
  dataloader_shuffle: true
  dataloader_num_workers: 1
  dataloader_batch_size: 8
  train:
    state: Train
    H_path: [ 'D:\Data\SIDD\train\groundtruth' ]
    L_path: [ 'D:\Data\SIDD\train\input' ]
    image_size: 128
  val:
    state: Val
    H_path: [ 'D:\Data\SIDD\val\groundtruth' ]
    L_path: [ 'D:\Data\SIDD\val\input' ]
net:
  type: restormer_baseline
  in_chans: 3
  dim: 48
  bias: False
  num_blocks: [ 4, 6, 6, 8 ]
  num_refinement_blocks: 4
  ffn_expansion_factor: 2.66
  LayerNorm_type: BiasFree
  attn_type: Window Attention
  attn_config:
    window_size: [ 8, 8, 8, 8 ]
    num_heads: [ 4, 4, 4, 4 ]
    qkv_bias: True
    qk_scale: null
    attn_drop: 0.
    proj_drop: 0.
optimizer:
  type: adamw
  learning_rate: 3.0e-4  # 学习率
  weight_decay: 1.0e-4  # 权重衰减
  betas: [ 0.9, 0.999 ]
  eps: 1.0e-8
criterion:
  type: 'charbonnier'
  eps: 1.0e-9
scheduler:
  type: CosineAnnealingRestartCyclicLR
  periods: [ 92000, 208000 ]
  restart_weights: [ 1,1 ]
  eta_mins: [ 0.0003,0.000001 ]
train:
  lossfn_weight: 1.0
  start_epoch: 1
  num_epochs: 300000
  checkpoint_val: 3000
  checkpoint_print: 50