task: 'uformer_denoising_color_sidd'
model: 'Uformer-T'
seed: 0
n_channels: 3  # 输入图像通道数
sigma: 15
path:
  pretrained_net: null
datasets:
  dataset_type: 'denoising'
  dataloader_shuffle: true
  dataloader_num_workers: 1
  dataloader_batch_size: 12
  train:
    state: 'Train'
    H_path: [ 'E:\Data\SIDD\train\groundtruth' ]
    L_path: [ 'E:\Data\SIDD\train\input' ]
    image_size: 128
  val:
    state: 'Val'
    H_path: [ 'E:\Data\SIDD\val\groundtruth' ]
    L_path: [ 'E:\Data\SIDD\val\input' ]
net:
  type: 'Uformer-T'
  img_size: 128
  embed_dim: 32
  window_size: 8
  token_projection: 'linear'
  token_mlp: 'leff'
  depths: [ 2, 2, 2, 2, 2, 2, 2, 2, 2 ]
  modulator: True
optimizer:
  type: 'adamw'
  learning_rate: 2.0e-4  # 学习率
  weight_decay: 0.02  # 权重衰减
  betas: [ 0.9, 0.999 ]
  eps: 1.0e-8
criterion:
  type: 'charbonnier'
  eps: 1.0e-9
scheduler:
  type: 'StepLR'
  step: 15
  gamma: 0.5
train:
  start_epoch: 0
  num_epochs: 70
  checkpoint_val: 1
  checkpoint_print: 1

  lossfn_weight: 1.0
  decay: 0.999
